# Generated by Django 2.2.12 on 2020-04-17 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiSPModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loai_sp', models.CharField(blank=True, max_length=50, verbose_name='Loại Sản Phẩn')),
                ('Link', models.CharField(max_length=50, verbose_name='Link')),
                ('Mo_ta', models.TextField(verbose_name='Mô Tả')),
                ('Trang_thai', models.BooleanField(verbose_name='Trạng Thái')),
            ],
        ),
        migrations.CreateModel(
            name='SanPhamModel',
            fields=[
                ('Ma_sp', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã Sản Phẩm')),
                ('Ten_sp', models.CharField(blank=True, max_length=50, verbose_name='Tên Sản Phẩm')),
                ('Mo_ta', models.TextField(verbose_name='Mô Tả')),
                ('Gia_nhap', models.IntegerField(blank=True, default=0, verbose_name='Giá Nhập')),
                ('Trang_thai', models.BooleanField(verbose_name='Trạng Thái')),
                ('Anh', models.ImageField(upload_to='media')),
                ('Loai_sp', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='San_Pham.LoaiSPModel')),
            ],
        ),
        migrations.CreateModel(
            name='SPBanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mo_ta', models.TextField(verbose_name='Mô Tả')),
                ('Gia_ban', models.IntegerField(blank=True, default=0, verbose_name='Giá Bán')),
                ('Gia_sale', models.IntegerField(default=0, verbose_name='Giá Sale')),
                ('Hang_ton', models.IntegerField(default=0, verbose_name='Hàng Tồn')),
                ('Trang_thai', models.BooleanField(verbose_name='Trạng Thái')),
                ('San_Pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='San_Pham.SanPhamModel')),
            ],
        ),
    ]
