# Generated by Django 2.2.12 on 2020-04-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('San_Pham', '0002_auto_20200417_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spbanmodel',
            name='Hang_ton',
            field=models.IntegerField(default=100, verbose_name='Hàng Tồn'),
        ),
    ]
