# Generated by Django 2.2.12 on 2020-04-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('San_Pham', '0003_auto_20200417_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spbanmodel',
            name='Gia_ban',
            field=models.IntegerField(blank=True, default=200000, verbose_name='Giá Bán'),
        ),
        migrations.AlterField(
            model_name='spbanmodel',
            name='Gia_sale',
            field=models.IntegerField(default=15000, verbose_name='Giá Sale'),
        ),
        migrations.AlterField(
            model_name='spbanmodel',
            name='Mo_ta',
            field=models.SmallIntegerField(choices=[(1, 'Đang Sale 10 %'), (2, 'Đang giảm mạnh'), (3, 'Đang Sale 50 %')], default=2, verbose_name='Mô Tả'),
        ),
    ]
