# Generated by Django 2.2.12 on 2020-04-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('San_Pham', '0005_auto_20200417_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spbanmodel',
            name='Gia_sale',
            field=models.IntegerField(default=150000, verbose_name='Giá Sale'),
        ),
    ]
